### ISSUE TITLE
How to confirm outreach from this project?

### ISSUE THREAD

**Issue by balloob** [ossf/great-mfa-project#49]
Home Assistant received this issue: https://github.com/home-assistant/core/issues/61455

The author's name is mentioned in your README by name, but that is easy to set on a different account. 

Is it legit?

**Comment by david-a-wheeler** [comment]
Yes, it's legit. It's hard to run a giveaway without making it look like a scam :-).

**Comment by david-a-wheeler** [comment]
You're right about names being easy to forge. I'll add the GitHub and/or GitLab account names next to people's names, that may help.
