### ISSUE TITLE
Initial Outreach to Maintainers: Figure out how we will initially reach out to our list of maintainers of critical projects to ask if they'd like to participate

### ISSUE THREAD

**Issue by jenniferfernick** [ossf/great-mfa-project#6]

**Comment by SecurityCRob** [comment]
David coordinated an export(1) of the OSSF's Critical Projects' work for us to work off of.

(1) - https://docs.google.com/spreadsheets/d/1sO_tJ_B7_2I-TUx23pnBoIRJIqaOm8yBnKAwqs7DwBw/edit#gid=0

**Comment by SecurityCRob** [comment]
Process has been defined
